# Generated by Django 5.1 on 2026-01-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('business_partner', '0016_alter_siteconfigs_notification_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='QyurateUser',
        ),
    ]
