# Generated by Django 5.1 on 2026-01-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_qyurateuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qyurateuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='qyurateuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='qyurateuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='qyurateuser',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='qyurateuser',
            name='username',
        ),
    ]
