# Generated by Django 5.1 on 2026-01-15 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_qyurateuser_options_alter_qyurateuser_managers_and_more'),
        ('business_partner', '0016_alter_siteconfigs_notification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='qyurateuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qyurateuser',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='business_partner.shop'),
        ),
    ]
