# Generated by Django 5.1 on 2025-11-07 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfigs',
            name='business_partner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_partner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shops', to='business_partner.user')),
            ],
        ),
        migrations.AddField(
            model_name='siteconfigs',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='site_configs', to='business_partner.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='business_partner.shop'),
        ),
        migrations.DeleteModel(
            name='BusinessPartner',
        ),
    ]
