# Generated by Django 5.1 on 2025-11-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0002_remove_siteconfigs_business_partner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfigs',
            old_name='theme_color',
            new_name='color_palette',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='siteconfigs',
            name='site_name',
        ),
    ]
