# Generated by Django 5.1 on 2025-11-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
