# Generated by Django 5.1 on 2025-11-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0005_alter_shop_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfigs',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='siteconfigs',
            name='logo',
        ),
        migrations.AddField(
            model_name='siteconfigs',
            name='hero_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfigs',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
