# Generated by Django 5.1 on 2025-11-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0006_remove_siteconfigs_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='domain',
            field=models.CharField(default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
