# Generated by Django 5.1 on 2026-01-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0007_shop_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siteconfigs',
            name='notification_method',
            field=models.CharField(choices=[('WOZZAP', 'whatsapp'), ('EMAIL', 'email')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
