# Generated by Django 5.1 on 2026-01-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0008_shop_email_shop_phone_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigs',
            name='color_palette',
            field=models.CharField(default='#FF6A07', max_length=7),
        ),
    ]
