# Generated by Django 5.1 on 2026-01-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0009_alter_siteconfigs_color_palette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigs',
            name='notification_method',
            field=models.CharField(choices=[('EMAIL', 'email'), ('WOZZAP', 'whatsapp')], max_length=50),
        ),
    ]
