# Generated by Django 5.1 on 2026-01-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0010_alter_siteconfigs_notification_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigs',
            name='notification_method',
            field=models.CharField(choices=[('WOZZAP', 'whatsapp'), ('EMAIL', 'email')], max_length=50),
        ),
    ]
