# Generated by Django 5.1 on 2026-03-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0016_alter_siteconfigs_notification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfigs',
            name='tier',
            field=models.CharField(choices=[('LITE', 'LITE'), ('STORE', 'STORE')], default='LITE', max_length=50),
        ),
    ]
