# Generated by Django 5.1 on 2026-04-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0018_alter_siteconfigs_notification_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfigs',
            name='notification_method',
            field=models.CharField(choices=[('EMAIL', 'email'), ('WOZZAP', 'whatsapp')], max_length=50),
        ),
    ]
