# Generated by Django 5.1 on 2024-11-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('imageSVG', models.TextField()),
                ('imageJSON', models.JSONField()),
                ('likes', models.IntegerField(default=0)),
                ('clicked', models.IntegerField(default=0)),
                ('description', models.TextField(null='')),
                ('templateOwner', models.CharField()),
            ],
        ),
    ]
