# Generated by Django 5.1 on 2024-11-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageJSON',
        ),
        migrations.RemoveField(
            model_name='product',
            name='templateOwner',
        ),
    ]
