# Generated by Django 5.1 on 2024-11-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_product_imagejson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageSVG',
        ),
        migrations.AddField(
            model_name='product',
            name='imageJSON',
            field=models.JSONField(default='jhhhgdg'),
            preserve_default=False,
        ),
    ]
