# Generated by Django 5.1 on 2024-11-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_remove_product_imagesvg_product_imagejson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageJSON',
            new_name='canvasJSON',
        ),
    ]
