# Generated by Django 5.1 on 2024-12-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_rename_imagejson_product_canvasjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canvasSVG',
            field=models.TextField(null=True),
        ),
    ]
