# Generated by Django 5.1 on 2024-12-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_product_canvassvg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canvasPNG',
            field=models.TextField(null=True),
        ),
    ]
