# Generated by Django 5.1 on 2024-12-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_product_canvaspng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('THEME', 'Theme'), ('GIFT THEME', 'Gift theme')])),
            ],
        ),
    ]
