# Generated by Django 5.1 on 2025-01-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ThemedProduct',
        ),
    ]
