# Generated by Django 5.1 on 2025-01-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_availableproducts_themedproduct_base_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproducts',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='availableproducts',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
