# Generated by Django 5.1 on 2025-02-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_availableproducts_base_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproducts',
            name='description',
            field=models.TextField(default='djfd', null=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availableproducts',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
