# Generated by Django 5.1 on 2025-02-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_availableproducts_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableproducts',
            old_name='base_image',
            new_name='base_image_url',
        ),
        migrations.RenameField(
            model_name='availableproducts',
            old_name='thumbnail_image',
            new_name='thumbnail_image_url',
        ),
        migrations.RenameField(
            model_name='themedproduct',
            old_name='base_product',
            new_name='base_product_url',
        ),
    ]
