# Generated by Django 5.1 on 2025-03-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_rename_base_image_availableproducts_base_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themedproduct',
            old_name='base_product_url',
            new_name='base_product',
        ),
    ]
