# Generated by Django 5.1 on 2025-11-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_rename_base_product_url_themedproduct_base_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableproducts',
            name='description',
            field=models.TextField(blank=True, null=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='type',
            field=models.CharField(choices=[('RANDOM THEME', 'Random theme'), ('GIFT THEME', 'Gift theme')], max_length=200),
        ),
    ]
