# Generated by Django 5.1 on 2025-12-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_alter_availableproducts_description_alter_theme_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('thumbnail_image_url', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('base_image_url', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='themedproduct',
            name='base_product',
        ),
        migrations.RemoveField(
            model_name='themedproduct',
            name='theme',
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('price', models.IntegerField()),
                ('canvasJSON', models.JSONField(null=True)),
                ('canvasSVG', models.TextField(null=True)),
                ('canvasPNG', models.TextField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('clicked', models.IntegerField(default=0)),
                ('base_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='themed_products', to='Products.product')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='Products.theme')),
            ],
        ),
        migrations.DeleteModel(
            name='AvailableProducts',
        ),
        migrations.DeleteModel(
            name='ThemedProduct',
        ),
    ]
