# Generated by Django 5.1 on 2025-12-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_product_remove_themedproduct_base_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='base_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='themed_products', to='Products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='theme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='Products.theme'),
            preserve_default=False,
        ),
    ]
