# Generated by Django 5.1 on 2025-12-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_alter_template_base_product_alter_template_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
