# Generated by Django 5.1 on 2025-12-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_product_base_product_product_canvasjson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_template',
        ),
    ]
