# Generated by Django 5.1 on 2025-12-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_remove_product_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
