# Generated by Django 5.1 on 2025-11-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0003_rename_theme_color_siteconfigs_color_palette_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
