# Generated by Django 5.1 on 2025-12-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0023_product_is_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('customer_email', models.EmailField(max_length=254, null=True)),
                ('customer_phone_no', models.CharField(max_length=20, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PROCESSING', 'Processing'), ('PENDING', 'Pending')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='Products.product')),
            ],
        ),
    ]
