# Generated by Django 5.1 on 2026-01-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_alter_order_guid_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guid',
            field=models.UUIDField(auto_created=True, blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PROCESSING', 'Processing')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='notification_method',
            field=models.CharField(choices=[('EMAIL', 'email'), ('WOZZAP', 'whatsapp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'success'), ('PENDING', 'Pending'), ('FAILED', 'failed')], default='PENDING'),
        ),
    ]
