# Generated by Django 5.1 on 2026-01-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_alter_order_guid_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guid',
            field=models.UUIDField(auto_created=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'failed'), ('SUCCESS', 'success')], default='PENDING'),
        ),
    ]
