# Generated by Django 5.1 on 2026-01-03 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_alter_order_guid_alter_ordernotificationlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='notification_method',
            field=models.CharField(choices=[('WOZZAP', 'whatsapp'), ('EMAIL', 'email')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'success'), ('FAILED', 'failed'), ('PENDING', 'Pending')], default='PENDING'),
        ),
    ]
