# Generated by Django 5.1 on 2026-01-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_alter_order_guid_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PROCESSING', 'Processing')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='notification_method',
            field=models.CharField(choices=[('EMAIL', 'email'), ('WOZZAP', 'whatsapp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='status',
            field=models.CharField(choices=[('FAILED', 'failed'), ('PENDING', 'Pending'), ('SUCCESS', 'success')], default='PENDING'),
        ),
    ]
