# Generated by Django 5.1 on 2026-01-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0014_alter_order_status_alter_ordernotificationlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='notification_method',
            field=models.CharField(choices=[('WOZZAP', 'whatsapp'), ('EMAIL', 'email')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='status',
            field=models.CharField(choices=[('FAILED', 'failed'), ('SUCCESS', 'success'), ('PENDING', 'Pending')], default='PENDING'),
        ),
    ]
