# Generated by Django 5.1 on 2026-01-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0015_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='notification_method',
            field=models.CharField(choices=[('EMAIL', 'email'), ('WOZZAP', 'whatsapp')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'success'), ('FAILED', 'failed'), ('PENDING', 'Pending')], default='PENDING'),
        ),
    ]
