# Generated by Django 5.1 on 2026-01-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0017_alter_order_status_alter_ordernotificationlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing')], default='PENDING', max_length=50),
        ),
    ]
