# Generated by Django 5.1 on 2026-01-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0019_alter_order_status_alter_ordernotificationlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PROCESSING', 'Processing'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'success'), ('PENDING', 'Pending'), ('FAILED', 'failed')], default='PENDING'),
        ),
    ]
