# Generated by Django 5.1 on 2026-03-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0020_alter_order_status_alter_ordernotificationlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'failed'), ('SUCCESS', 'success')], default='PENDING'),
        ),
    ]
