# Generated by Django 5.1 on 2026-04-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='notification_method',
            field=models.CharField(choices=[('WOZZAP', 'whatsapp'), ('EMAIL', 'email')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'success'), ('FAILED', 'failed'), ('PENDING', 'Pending')], default='PENDING'),
        ),
    ]
