# Generated by Django 5.1 on 2026-05-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0025_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotificationlog',
            name='status',
            field=models.CharField(choices=[('FAILED', 'failed'), ('PENDING', 'Pending'), ('SUCCESS', 'success')], default='PENDING'),
        ),
    ]
