# Generated by Django 5.1 on 2025-01-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0013_availableproducts_base_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('stock_image', models.ImageField(blank=True, null=True, upload_to='stockImages/')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stockImages', to='Products.theme')),
            ],
        ),
    ]
