# Generated by Django 5.1 on 2025-01-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockimage',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
