# Generated by Django 5.1 on 2025-02-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_stockimage_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockimage',
            old_name='stock_image',
            new_name='stock_image_url',
        ),
    ]
